version: '3.8'

services:

  mysql:
    container_name: 'mysql-db'
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'findar_book_app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '7000:3306'
    networks:
      - loki
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: 'findar_book_app'
    image: 'findar_book_app:latest'
    links:
      - mysql
    depends_on:
       mysql:
         condition: service_healthy
    networks:
      - loki

networks:
  loc-net:
    driver: bridge
