services:

  mysql:
    container_name: 'findar_book_app_db'
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'findar_book_app'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - './data/db:/var/lib/mysql'
    networks:
      - loc-net


  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: 'findar_book_app'
    image: 'findar_book_app:latest'
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - loc-net

networks:
  loc-net:
    driver: bridge

