server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://mysql-db:3306/findar_book_app
#    url: jdbc:mysql://localhost:3306/findar_book_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
